### ISSUE TITLE
Implement a C^k with k>2 coupling layer with numerical inverse and implicit function theorem.

### ISSUE THREAD

**Issue by EiffL** [astrodeepnet/sbi_experiments#7]
I'm opening this issue to discuss an idea from #2 to try to use the implicit function theorem to define the inverse and jacobian of general bijections, in order to have a general way of defining smooth coupling layers.

@b-remy had some examples at some point of how to do that in JAX, before we switched to TF. Do you still have your JAX prototype Benjamin?

**Comment by b-remy** [comment]
Hi there!

Yes, and I just adapted the example @Justinezgh proposed in #2. It seems to work well and quit fast, and for many k>2!

Some examples with `a = 1`,  `b = 1` and `c = 0.5`:
<img width="352" alt="Capture d’écran 2021-12-12 à 01 36 52" src="https://user-images.githubusercontent.com/30293694/145696172-524dc402-0a74-4893-a1c6-a4d285e8e263.png">
<img width="372" alt="Capture d’écran 2021-12-12 à 01 38 43" src="https://user-images.githubusercontent.com/30293694/145696210-6ad6f93c-bf43-47ca-8a6c-f3764d57527c.png">

Code here: https://colab.research.google.com/drive/1bULsH6McxKy_IqViRpx0IgvCfnnSlwGp?usp=sharing

**Comment by EiffL** [comment]
![giphy (3)](https://user-images.githubusercontent.com/861591/145708578-c068bb0f-e5f5-4bd9-9dfa-4a0ca082e5ca.gif)

**Comment by EiffL** [comment]
ok, so.... almost there. I have added the corrercted couplping layer in #10 and it's training \o/ buuuut it's giving me some weird reresuts
![image](https://user-images.githubusercontent.com/861591/146111443-b808571e-bd81-4ff0-8cd3-b64221d3ffa2.png)

there must be somehiing wrong, maybe in the logdet computationn....

**Comment by EiffL** [comment]
Ok i think this is done, will be closed as soon as we merge #10.
